#ifndef EVDSET_H
#define EVDSET_H

#include <Arduino.h>

inline String getWebPageTemplate(
    const char* theme_mode, const char* friendly_name, const char* mdns_target_host,
    const char* wifi_ssid, const char* wifi_pass, bool use_static_ip,
    const char* static_ip_str, const char* static_gw_str, const char* static_sn_str, const char* static_dns_str,
    int pin_lrc, int pin_dout, int pin_bclk,
    int pin_aux_lrc = 0, int pin_aux_din = 0, int pin_aux_bclk = 0,
    int pin_bt_lrc = 0, int pin_bt_din = 0, int pin_bt_bclk = 0,
    float node_volume_multiplier = 1.0f
) {
    int globalVolPercent = (int)(node_volume_multiplier * 100.0f);
    if (globalVolPercent < 0) globalVolPercent = 0;
    if (globalVolPercent > 100) globalVolPercent = 100;

    String html = "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<title>Enkelvoud Server Settings</title>"
        "<style>"
        ":root { --bg-color: #0f172a; --card-bg: #1e293b; --border-color: #334155; --text-color: #ffffff; --accent-color: #0284c7; --accent-hover: #026aa2; }"
        "body.theme-black { --bg-color: #000000; --card-bg: #111111; --border-color: #222222; --text-color: #f8fafc; --accent-color: #3b82f6; --accent-hover: #2563eb; }"
        "body.theme-blue { --bg-color: #0f172a; --card-bg: #1e293b; --border-color: #334155; --text-color: #fff; --accent-color: #0284c7; --accent-hover: #026aa2; }"
        "body.theme-light { --bg-color: #f1f5f9; --card-bg: #ffffff; --border-color: #cbd5e1; --text-color: #0f172a; --accent-color: #2563eb; --accent-hover: #1d4ed8; }"
        "body { font-family: sans-serif; background: var(--bg-color); color: var(--text-color); padding: 20px; margin: 0; transition: background 0.3s, color 0.3s; }"
        ".container { max-width: 600px; margin: 0 auto; background: var(--card-bg); border: 1px solid var(--border-color); border-radius: 8px; padding: 24px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }"
        ".header-container { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid var(--border-color); padding-bottom: 12px; margin-bottom: 16px; gap: 12px; flex-wrap: wrap; }"
        "h2 { margin: 0; font-size: 22px; }"
        ".header-selectors { display: flex; gap: 8px; align-items: center; }"
        ".top-theme-select, select, input[type='text'], input[type='password'], input[type='number'] { font-size: 14px; padding: 10px; box-sizing: border-box; background: var(--bg-color); color: var(--text-color); border: 1px solid var(--border-color); border-radius: 6px; }"
        ".top-theme-select { width: 120px; }"
        "label { display: block; margin-top: 12px; font-size: 14px; font-weight: 600; }"
        ".row-group { display: flex; gap: 10px; align-items: center; }"
        ".row-group input { flex: 1; }"
        ".btn { background: var(--accent-color); color: #fff; font-weight: bold; cursor: pointer; border: none; padding: 10px 16px; border-radius: 6px; text-align: center; display: inline-block; transition: background 0.2s; margin-top: 10px; }"
        ".btn:hover { background: var(--accent-hover); }"
        ".btn:disabled { background: #475569; opacity: 0.6; cursor: not-allowed; }"
        ".btn-secondary { background: #475569; color: #fff; }"
        ".btn-secondary:hover { background: #334155; }"
        ".button-row { display: flex; gap: 10px; margin-top: 20px; }"
        ".checkbox-label { display: flex; align-items: center; gap: 10px; margin-top: 12px; cursor: pointer; font-weight: normal; }"
        ".checkbox-label input { width: 18px; height: 18px; accent-color: var(--accent-color); }"
        ".collapsible-section { border: 1px solid var(--border-color); border-radius: 6px; margin-top: 12px; background: var(--bg-color); overflow: hidden; }"
        ".collapsible-header { display: flex; justify-content: space-between; align-items: center; padding: 12px 16px; background: var(--card-bg); cursor: pointer; font-weight: bold; font-size: 15px; }"
        ".collapsible-header:hover { background: var(--border-color); }"
        ".collapsible-content { padding: 16px; display: none; border-top: 1px solid var(--border-color); }"
        ".collapsible-content.open { display: block; }"
        ".arrow { transition: transform 0.2s; }"
        ".arrow.open { transform: rotate(180deg); }"
        ".range-slider-group { margin-top: 10px; width: 100%; box-sizing: border-box; }"
        ".range-slider-group label { font-size: 12px; font-weight: normal; display: flex; justify-content: space-between; width: 100%; }"
        ".range-with-input { position: relative; width: 100%; height: 35px; display: flex; align-items: center; margin-top: 4px; box-sizing: border-box; }"
        ".range-with-input input[type='range'] { position: absolute; left: 0; right: 0; width: 100%; background: none; -webkit-appearance: none; appearance: none; margin: 0; outline: none; z-index: 2; box-sizing: border-box; }"
        ".range-with-input input[type='range']::-webkit-slider-runnable-track { background: none; height: 6px; }"
        ".range-with-input input[type='range']::-webkit-slider-thumb { appearance: none; -webkit-appearance: none; height: 18px; width: 18px; border-radius: 50%; background: var(--accent-color); border: 2px solid #fff; cursor: pointer; pointer-events: auto; margin-top: -6px; }"
        ".slider-track-bg { position: absolute; left: 0; right: 0; height: 6px; background: var(--border-color); border-radius: 3px; }"
        ".slider-track-fill { position: absolute; height: 6px; background: var(--accent-color); border-radius: 3px; }"
        ".global-volume-card { background: var(--bg-color); border: 1px solid var(--border-color); border-radius: 6px; padding: 12px; margin-top: 15px; width: 100%; box-sizing: border-box; }"
        ".pinout-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }"
        ".pinout-column h4 { margin: 0 0 8px 0; font-size: 13px; color: var(--accent-color); text-transform: uppercase; }"
        ".modal-overlay { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.7); justify-content: center; align-items: center; z-index: 1000; }"
        ".modal { background: var(--card-bg); border: 1px solid var(--border-color); padding: 24px; border-radius: 8px; width: 90%; max-width: 400px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }"
        ".close-modal { background: #ef4444; margin-top: 16px; }"
        ".close-modal:hover { background: #dc2626; }"
        "#statusBanner { background: var(--bg-color); border: 1px solid var(--border-color); padding: 8px 12px; border-radius: 6px; font-size: 13px; margin-bottom: 15px; color: var(--accent-color); display: flex; align-items: center; justify-content: space-between; }"
        "</style></head>"
        "<body class='" + String(theme_mode) + "'>"
        "<div class='container'>"
        
        "<form id='setupForm' onkeydown='if(event.key === \"Enter\") { event.preventDefault(); return false; }'>"
        
        "<div class='header-container'>"
        "<div style='display: flex; align-items: center; gap: 10px;'>"
        "<a href='/' class='btn btn-secondary' style='margin-top:0; padding: 6px 12px; font-size: 13px; text-decoration: none;'>&larr; Back</a>"
        "<h2>Enkelvoud Server Settings</h2>"
        "</div>"
        "<div class='header-selectors'>"
        "<select id='themeSelect' class='top-theme-select' name='theme_mode' onchange='changeTheme(this.value)'>"
        "<option value='theme-black' " + String(String(theme_mode) == "theme-black" ? "selected" : "") + ">Black</option>"
        "<option value='theme-blue' " + String(String(theme_mode) == "theme-blue" ? "selected" : "") + ">Blue</option>"
        "<option value='theme-light' " + String(String(theme_mode) == "theme-light" ? "selected" : "") + ">Light</option>"
        "</select>"
        "</div>"
        "</div>"

        "<div id='statusBanner'>"
        "<span>Status: <strong id='statusText'>Ready</strong></span>"
        "<span id='statusSubtext' style='color: #94a3b8; font-size: 11px;'></span>"
        "</div>"

        "<div class='global-volume-card'>"
        "<div class='range-slider-group' style='margin-top:0;'>"
        "<label>Global Server Volume: <span id='globalVolVal'>" + String(globalVolPercent) + "</span>%</label>"
        "<div class='range-with-input'>"
        "<div class='slider-track-bg'></div>"
        "<div class='slider-track-fill' id='globalTrackFill' style='left: 0%; right: " + String(100 - globalVolPercent) + "%;'></div>"
        "<input type='range' name='node_vol' id='globalVolRange' min='0' max='100' value='" + String(globalVolPercent) + "' oninput=\"updateValDisplay('globalVolVal', this.value); updateGlobalVolumeSliderUI(this.value);\" onchange=\"updateGlobalVolume(this.value);\">"
        "</div>"
        "</div>"
        "</div>"

        "<div class='collapsible-section'>"
        "<div class='collapsible-header' onclick='toggleSection(\"netSection\", \"netArrow\")'>"
        "<span>Network</span>"
        "<span id='netArrow' class='arrow'>&#9660;</span>"
        "</div>"
        "<div id='netSection' class='collapsible-content'>"
        "<label style='font-size: 15px; color: var(--accent-color);'>Server Hostname: Enkelvoud</label>"
        "<input type='hidden' name='mdns_host' value='Enkelvoud'>"
        "<label>Wi-Fi SSID:</label>"
        "<div class='row-group'>"
        "<input type='text' id='ssidInput' name='ssid' value='" + String(wifi_ssid) + "' placeholder='Enter manually or search'>"
        "<button type='button' class='btn' style='margin-top:0;' onclick='openWifiModal()'>Wi-Fi Search</button>"
        "</div>"
        "<label>Wi-Fi Password:</label>"
        "<div class='row-group'>"
        "<input type='password' id='passInput' name='pass' value='" + String(wifi_pass) + "'>"
        "<button type='button' id='testBtn' class='btn btn-secondary' style='margin-top:0;' onclick='testWifiConnection()'>Test connection</button>"
        "</div>"
        "<div id='wifiTestResult' style='font-size: 13px; margin-top: 6px;'></div>"
        "<label class='checkbox-label'>"
        "<input type='checkbox' id='staticCheck' name='use_static' " + String(use_static_ip ? "checked" : "") + " onchange='toggleStaticIp()'> Use Static IP Configuration"
        "</label>"
        "<div id='staticIpFields' style='display: " + String(use_static_ip ? "block" : "none") + ";'>"
        "<label>Static IP Address:</label>"
        "<input type='text' id='staticIpInput' name='static_ip' value='" + String(static_ip_str) + "' oninput='autoFillNetworkDefaults()'>"
        "<label>Gateway IP:</label>"
        "<input type='text' id='gatewayInput' name='static_gw' value='" + String(static_gw_str) + "'>"
        "<label>Subnet Mask:</label>"
        "<input type='text' id='subnetInput' name='static_sn' value='" + String(static_sn_str) + "'>"
        "<label>DNS Server:</label>"
        "<input type='text' id='dnsInput' name='static_dns' value='" + String(static_dns_str) + "'>"
        "</div>"
        "</div>"
        "</div>"

        "<div class='collapsible-section'>"
        "<div class='collapsible-header' onclick='toggleSection(\"dacSection\", \"dacArrow\")'>"
        "<span>DAC Pinouts</span>"
        "<span id='dacArrow' class='arrow'>&#9660;</span>"
        "</div>"
        "<div id='dacSection' class='collapsible-content'>"
        "<div class='pinout-column'>"
        "<h4>DAC (Speaker Out)</h4>"
        "<label>LRC Pin:</label><input type='number' name='lrc' value='" + String(pin_lrc) + "'>"
        "<label>DOUT Pin:</label><input type='number' name='dout' value='" + String(pin_dout) + "'>"
        "<label>BCLK Pin:</label><input type='number' name='bclk' value='" + String(pin_bclk) + "'>"
        "</div>"
        "</div>"
        "</div>"

        "<div class='collapsible-section'>"
        "<div class='collapsible-header' onclick='toggleSection(\"audioInSec\", \"audioInArrow\")'>"
        "<span>Audio Inputs Pinouts</span>"
        "<span id='audioInArrow' class='arrow'>&#9660;</span>"
        "</div>"
        "<div id='audioInSec' class='collapsible-content'>"
        "<div class='pinout-grid'>"
        "<div class='pinout-column'>"
        "<h4>Aux In (PCM1808)</h4>"
        "<label>LRC Pin:</label><input type='number' name='aux_lrc' value='" + String(pin_aux_lrc) + "'>"
        "<label>DIN Pin:</label><input type='number' name='aux_din' value='" + String(pin_aux_din) + "'>"
        "<label>BCLK Pin:</label><input type='number' name='aux_bclk' value='" + String(pin_aux_bclk) + "'>"
        "</div>"
        "<div class='pinout-column'>"
        "<h4>Bluetooth Receiver (ESP32)</h4>"
        "<label>LRC Pin:</label><input type='number' name='bt_lrc' value='" + String(pin_bt_lrc) + "'>"
        "<label>DIN Pin:</label><input type='number' name='bt_din' value='" + String(pin_bt_din) + "'>"
        "<label>BCLK Pin:</label><input type='number' name='bt_bclk' value='" + String(pin_bt_bclk) + "'>"
        "</div>"
        "</div>"
        "</div>"
        "</div>"

        "<label class='checkbox-label' style='margin-top:20px;'>"
        "<input type='checkbox' name='reset_defaults'> Reset to default settings"
        "</label>"

        "<div class='button-row'>"
        "<button type='button' class='btn' onclick='submitForm()' style='flex:1; margin-top:0;'>Save and Close</button>"
        "<button type='button' class='btn btn-secondary' onclick='handleCancel()' style='flex:1; margin-top:0;'>Cancel</button>"
        "</div>"
        "</form></div>"

        "<div class='modal-overlay' id='wifiModal'>"
        "<div class='modal'>"
        "<h3>Available Wi-Fi Networks</h3>"
        "<p style='font-size: 13px; color: #94a3b8;'>Select a network to auto-fill the SSID:</p>"
        "<div id='wifiList' style='max-height: 150px; overflow-y: auto; border: 1px solid var(--border-color); padding: 8px; border-radius: 4px;'>Scanning...</div>"
        "<button type='button' class='btn close-modal' onclick='closeWifiModal()'>Close</button>"
        "</div></div>"

        "<script>"
        "function setStatus(text, sub = '') {"
        "  document.getElementById('statusText').innerText = text;"
        "  document.getElementById('statusSubtext').innerText = sub;"
        "}"
        "function changeTheme(themeClass) {"
        "  document.body.className = themeClass;"
        "  setStatus('Theme changed', themeClass);"
        "}"
        "function toggleSection(contentId, arrowId) {"
        "  const content = document.getElementById(contentId);"
        "  const arrow = document.getElementById(arrowId);"
        "  content.classList.toggle('open');"
        "  arrow.classList.toggle('open');"
        "  setStatus('Section toggled', contentId);"
        "}"
        "function toggleStaticIp() {"
        "  const isChecked = document.getElementById('staticCheck').checked;"
        "  document.getElementById('staticIpFields').style.display = isChecked ? 'block' : 'none';"
        "  setStatus('Static IP config', isChecked ? 'Enabled' : 'Disabled');"
        "}"
        "function autoFillNetworkDefaults() {"
        "  const ipVal = document.getElementById('staticIpInput').value;"
        "  const parts = ipVal.split('.');"
        "  if (parts.length === 4) {"
        "    const baseSubnet = `${parts[0]}.${parts[1]}.${parts[2]}`;"
        "    document.getElementById('gatewayInput').value = `${baseSubnet}.1`;"
        "    document.getElementById('subnetInput').value = '255.255.255.0';"
        "    document.getElementById('dnsInput').value = `${baseSubnet}.1`;"
        "    setStatus('Network defaults auto-filled', baseSubnet);"
        "  }"
        "}"
        "function openWifiModal() {"
        "  document.getElementById('wifiModal').style.display = 'flex';"
        "  setStatus('Scanning Wi-Fi networks...');"
        "  fetch('/scan').then(res => res.json()).then(data => {"
        "    let listHtml = '';"
        "    data.forEach(net => {"
        "      listHtml += `<div style='padding: 6px; cursor: pointer; border-bottom: 1px solid var(--border-color);' onclick=\"selectWifi('${net.ssid}')\">${net.ssid} (${net.rssi} dBm)</div>`;"
        "    });"
        "    document.getElementById('wifiList').innerHTML = listHtml || 'No networks found. ';"
        "    setStatus('Wi-Fi scan complete', data.length + ' networks found');"
        "  }).catch(err => {"
        "    setStatus('Wi-Fi scan failed');"
        "  });"
        "}"
        "function closeWifiModal() { document.getElementById('wifiModal').style.display = 'none'; setStatus('Ready'); }"
        "function selectWifi(ssidName) { document.getElementById('ssidInput').value = ssidName; closeWifiModal(); setStatus('SSID Selected', ssidName); }"
        "function updateValDisplay(spanId, val) { document.getElementById(spanId).innerText = val; }"
        
        "function updateGlobalVolumeSliderUI(val) {"
        "  const fill = document.getElementById('globalTrackFill');"
        "  const pct = parseInt(val);"
        "  fill.style.left = '0%';"
        "  fill.style.right = (100 - pct) + '%';"
        "  setStatus('Adjusting Volume', pct + '%');"
        "}"

        "function testWifiConnection() {"
        "  const ssid = document.getElementById('ssidInput').value;"
        "  const pass = document.getElementById('passInput').value;"
        "  const resultEl = document.getElementById('wifiTestResult');"
        "  const testBtn = document.getElementById('testBtn');"
        
        "  testBtn.disabled = true;"
        "  resultEl.style.color = '#94a3b8';"
        "  resultEl.innerText = 'Testing connection...';"
        "  setStatus('Testing Wi-Fi...', ssid);"
        
        "  fetch('/api/test_wifi', {"
        "    method: 'POST',"
        "    headers: { 'Content-Type': 'application/json' },"
        "    body: JSON.stringify({ ssid: ssid, pass: pass })"
        "  }).then(res => res.json()).then(data => {"
        "    testBtn.disabled = false;"
        "    if (data.success) {"
        "      resultEl.style.color = '#22c55e';"
        "      resultEl.innerText = 'Success: Connected to ' + ssid;"
        "      setStatus('Wi-Fi Connected', ssid);"
        "    } else {"
        "      resultEl.style.color = '#ef4444';"
        "      resultEl.innerText = 'Failed: ' + (data.message || 'Check credentials');"
        "      setStatus('Wi-Fi Test Failed', data.message);"
        "    }"
        "  }).catch(err => {"
        "    testBtn.disabled = false;"
        "    resultEl.style.color = '#ef4444';"
        "    resultEl.innerText = 'Connection test error';"
        "    setStatus('Wi-Fi Test Error');"
        "  });"
        "}"

        "function updateGlobalVolume(val) {"
        "  const multiplier = parseInt(val) / 100.0;"
        "  setStatus('Saving Volume', val + '%');"
        "  fetch('/api/volume', {"
        "    method: 'POST',"
        "    headers: { 'Content-Type': 'application/json' },"
        "    body: JSON.stringify({ volume: multiplier })"
        "  }).then(() => {"
        "    setStatus('Volume Updated', val + '%');"
        "  }).catch(err => {"
        "    console.error('Failed to update global volume:', err);"
        "    setStatus('Volume Update Failed');"
        "  });"
        "}"
        
        "function submitForm() {"
        "  setStatus('Saving settings...');"
        "  const formData = new URLSearchParams(new FormData(document.getElementById('setupForm')));"
        "  fetch('/save', { "
        "    method: 'POST', "
        "    headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, "
        "    body: formData "
        "  }).then(() => {"
        "    setStatus('Saved successfully! Restarting...');"
        "    alert('Settings saved. Server is restarting...');"
        "    setTimeout(() => { window.location.href = '/'; }, 3000);"
        "  }).catch(err => {"
        "    console.error('Save failed:', err);"
        "    setStatus('Save failed');"
        "    window.location.href = '/';"
        "  });"
        "}"

        "function handleCancel() {"
        "  setStatus('Cancelling changes...');"
        "  fetch('/cancel', { method: 'POST' }).then(() => {"
        "    window.location.href = '/';"
        "  }).catch(err => {"
        "    console.error('Cancel failed:', err);"
        "    window.location.href = '/';"
        "  });"
        "}"

        "window.onload = function() {"
        "  updateGlobalVolumeSliderUI(" + String(globalVolPercent) + ");"
        "  setStatus('Ready');"
        "};"
        "</script></body></html>";

    return html;
}

#endif